# netlify.toml
[build]
  # Dossier de publication (optionnel si les fichiers sont à la racine)
  publish = "."
  
  # Commande de build (optionnel pour un site statique)
  # command = "npm run build"

[build.environment]
  # Variables d'environnement pour le build
  NODE_VERSION = "18"

# Redirections et règles
[[redirects]]
  # Redirection pour les routes inexistantes vers la page d'accueil
  from = "/*"
  to = "/index.html"
  status = 404

# Headers pour la sécurité
[[headers]]
  for = "/*"
  [headers.values]
    # Sécurité
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Configuration des fonctions (si nécessaire plus tard)
[functions]
  directory = "netlify/functions"